# Generated by Django 2.2.8 on 2020-03-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discription',
            new_name='description',
        ),
    ]
