# Generated by Django 2.2.8 on 2020-03-23 23:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200324_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
