# Generated by Django 2.2.8 on 2020-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200411_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='21565486', max_length=20),
            preserve_default=False,
        ),
    ]
